travis:
  secure:
    BINSTAR_TOKEN: gqo0KALWzYzR2u2/xTfanle0MFroMl7gkW5ovj7Nd/z8eO7+3ucaTZS+VSCpy4x7c6RNYREfLCW8xc6s1SyIsMX0cDiRCJfrr1j8lSO9TSOLv0MhdWzf1aWfIIjuydOBGwlgBT5za+YLvP4mFc7b1dNC9V/8jz6d8b+O8KsGs5atTyknm6Aa7p2AcL7AwHVjWXvPufbTuw5vZRZaxQ+CiuozPmEkpO3NAyU3RRc8jKOgJKL4ix3DqO/kcFB9Vh5Xs1jRG2bfrLGiQ7mZCHn5Q2UosB1AD95eOYXYyv1XJb0SUuZ7O1oG11FlXg08RE+u25tmChEGdE+pnAHd4iOPV/J06dozwrLfvP1cYSrFpOgJdyoFCbtw53sK2Fhb/61WOogrWCCzCyiMErnGKFcOztv7LJeThbSY8QztTmTtZxKtzCteg6O4yuR19VPjL8kYdYPzOZvM8Vzh32+E9d+jhVhp1TqKaSTA9xX+WsIyTXM3dVUqXQ3lT4zio6JsCONDv5tKB6Ou2k6P/4lsdtQYCo9HTQFlym1smzB32+KSgGASJU4HKEYtg1W3/2b+DsApiQJHn/FnlGbpxkEogSOSCOQQc7Ql71i7nyEMAKWaXrwWwSNK+9UfzTdc64dZeZFYszb+m/+CkzzcWNhxjZ5aAkzPi78JYmXBfL5gPazuURw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
